export const defualtImages = [
  {
    id: "f6FdIjVW5ow",
    slug: "silhouette-photo-of-mountain-f6FdIjVW5ow",
    alternative_slugs: {
      en: "silhouette-photo-of-mountain-f6FdIjVW5ow",
      es: "foto-de-silueta-de-montana-f6FdIjVW5ow",
      ja: "山のシルエット写真-f6FdIjVW5ow",
      fr: "photo-de-silhouette-de-montagne-f6FdIjVW5ow",
      it: "foto-silhouette-di-montagna-f6FdIjVW5ow",
      ko: "실루엣-사진-산의-f6FdIjVW5ow",
      de: "silhouettenfoto-des-berges-f6FdIjVW5ow",
      pt: "foto-da-silhueta-da-montanha-f6FdIjVW5ow",
    },
    created_at: "2018-01-19T22:19:00Z",
    updated_at: "2024-07-26T12:09:02Z",
    promoted_at: "2018-01-20T13:17:23Z",
    width: 4626,
    height: 3084,
    color: "#4073c0",
    blur_hash: "LlD]oTE3WAoLk]adoJWV0g$yoMWV",
    description:
      "The image was taken one of my recent hiking trips to Majorca, in the mountain range Serra de Tramuntana. We went fast-packing, minimalistic gear, no tent .. falling asleep under the stars and waking up experiencing this sunrise. The morning light was motivation enough to leave my cozy sleeping bag to capture the image.",
    alt_description: "silhouette photo of mountain",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1516399880527-53ac841bf2d9?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1516399880527-53ac841bf2d9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1516399880527-53ac841bf2d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1516399880527-53ac841bf2d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1516399880527-53ac841bf2d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1516399880527-53ac841bf2d9",
    },
    links: {
      self: "https://api.unsplash.com/photos/silhouette-photo-of-mountain-f6FdIjVW5ow",
      html: "https://unsplash.com/photos/silhouette-photo-of-mountain-f6FdIjVW5ow",
      download:
        "https://unsplash.com/photos/f6FdIjVW5ow/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/f6FdIjVW5ow/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 301,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "Ub9iO4Yjq7M",
      updated_at: "2024-05-21T23:11:50Z",
      username: "markusvoetter",
      name: "Markus Voetter",
      first_name: "Markus",
      last_name: "Voetter",
      twitter_username: "markus_voetter",
      portfolio_url: "https://www.instagram.com/markusvoetter",
      bio: "Professional photographer based on Ireland's fascinating west coast. Markus Voetter is available for hire and happy to travel. Fine Art Prints available for sale. Contact Markus on Instagram @markusvoetter or via email at markusvoetter@gmail.com",
      location: "Kinvara, Ireland",
      links: {
        self: "https://api.unsplash.com/users/markusvoetter",
        html: "https://unsplash.com/@markusvoetter",
        photos: "https://api.unsplash.com/users/markusvoetter/photos",
        likes: "https://api.unsplash.com/users/markusvoetter/likes",
        portfolio: "https://api.unsplash.com/users/markusvoetter/portfolio",
        following: "https://api.unsplash.com/users/markusvoetter/following",
        followers: "https://api.unsplash.com/users/markusvoetter/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1515423425145-516544f69f4c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1515423425145-516544f69f4c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1515423425145-516544f69f4c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "markusvoetter",
      total_collections: 0,
      total_likes: 17,
      total_photos: 11,
      total_promoted_photos: 10,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: false,
      for_hire: false,
      social: {
        instagram_username: "markusvoetter",
        portfolio_url: "https://www.instagram.com/markusvoetter",
        twitter_username: "markus_voetter",
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X100T",
      name: "FUJIFILM, X100T",
      exposure_time: "1/18",
      aperture: "16.0",
      focal_length: "23.0",
      iso: 200,
    },
    location: {
      name: "Serra de Tramuntana, Spain",
      city: null,
      country: "Spain",
      position: {
        latitude: 39.5837186,
        longitude: 2.49999179999998,
      },
    },
    views: 9432301,
    downloads: 8367,
  },
  {
    id: "CkhXvEbKL8U",
    slug: "brown-mountains-under-white-sky-CkhXvEbKL8U",
    alternative_slugs: {
      en: "brown-mountains-under-white-sky-CkhXvEbKL8U",
      es: "montanas-marrones-bajo-el-cielo-blanco-CkhXvEbKL8U",
      ja: "白い空の下の茶色の山々-CkhXvEbKL8U",
      fr: "montagnes-brunes-sous-un-ciel-blanc-CkhXvEbKL8U",
      it: "montagne-marroni-sotto-il-cielo-bianco-CkhXvEbKL8U",
      ko: "흰-하늘-아래-갈색-산-CkhXvEbKL8U",
      de: "braune-berge-unter-weissem-himmel-CkhXvEbKL8U",
      pt: "montanhas-marrons-sob-o-ceu-branco-CkhXvEbKL8U",
    },
    created_at: "2019-04-21T21:33:20Z",
    updated_at: "2024-08-01T09:16:26Z",
    promoted_at: "2019-04-24T05:51:37Z",
    width: 3781,
    height: 5672,
    color: "#d9d9d9",
    blur_hash: "LuJ*I?xuayay_NkCayf6?asofkkC",
    description: null,
    alt_description: "brown mountains under white sky",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1555882173-6f8723703798?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1555882173-6f8723703798?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1555882173-6f8723703798?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1555882173-6f8723703798?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1555882173-6f8723703798?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1555882173-6f8723703798",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-mountains-under-white-sky-CkhXvEbKL8U",
      html: "https://unsplash.com/photos/brown-mountains-under-white-sky-CkhXvEbKL8U",
      download:
        "https://unsplash.com/photos/CkhXvEbKL8U/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/CkhXvEbKL8U/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 124,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "TUgIY0zKEaM",
      updated_at: "2024-06-04T15:59:35Z",
      username: "ztanable",
      name: "Zachary Tan",
      first_name: "Zachary",
      last_name: "Tan",
      twitter_username: null,
      portfolio_url: "http://ztanable.squarespace.com",
      bio: "Currently creating in Los Angeles, California // Singapore-born, Malaysian raised // On Instagram @ztanable",
      location: "Los Angeles, California",
      links: {
        self: "https://api.unsplash.com/users/ztanable",
        html: "https://unsplash.com/@ztanable",
        photos: "https://api.unsplash.com/users/ztanable/photos",
        likes: "https://api.unsplash.com/users/ztanable/likes",
        portfolio: "https://api.unsplash.com/users/ztanable/portfolio",
        following: "https://api.unsplash.com/users/ztanable/following",
        followers: "https://api.unsplash.com/users/ztanable/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1555881022277-d72ce8f82db9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1555881022277-d72ce8f82db9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1555881022277-d72ce8f82db9?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "ztanable",
      total_collections: 3,
      total_likes: 105,
      total_photos: 43,
      total_promoted_photos: 14,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "ztanable",
        portfolio_url: "http://ztanable.squarespace.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "NIKON CORPORATION",
      model: "NIKON D7200",
      name: "NIKON CORPORATION, NIKON D7200",
      exposure_time: "1/800",
      aperture: "4.0",
      focal_length: "30.0",
      iso: 500,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 3306162,
    downloads: 5017,
  },
  {
    id: "aQK3e0mH1g0",
    slug: "brown-and-white-mountains-under-blue-sky-during-daytime-aQK3e0mH1g0",
    alternative_slugs: {
      en: "brown-and-white-mountains-under-blue-sky-during-daytime-aQK3e0mH1g0",
      es: "montanas-marrones-y-blancas-bajo-el-cielo-azul-durante-el-dia-aQK3e0mH1g0",
      ja: "昼間の青空に茶色と白の山々-aQK3e0mH1g0",
      fr: "montagnes-brunes-et-blanches-sous-le-ciel-bleu-pendant-la-journee-aQK3e0mH1g0",
      it: "montagne-marroni-e-bianche-sotto-il-cielo-blu-durante-il-giorno-aQK3e0mH1g0",
      ko: "낮에는-푸른-하늘-아래-갈색과-흰색-산-aQK3e0mH1g0",
      de: "braune-und-weisse-berge-unter-blauem-himmel-tagsuber-aQK3e0mH1g0",
      pt: "montanhas-marrons-e-brancas-sob-o-ceu-azul-durante-o-dia-aQK3e0mH1g0",
    },
    created_at: "2020-09-12T05:18:12Z",
    updated_at: "2024-08-01T09:40:10Z",
    promoted_at: "2020-09-14T17:00:01Z",
    width: 3456,
    height: 5184,
    color: "#402626",
    blur_hash: "L~FZjZWXo1j[T#fRaza#ERo0oLj[",
    description:
      "The immensity of the desert is overwhelming, and many people take it for granted. It's fascinating how the shadows drawn on the dunes change right in front of our eyes throughout the day, how the ripples on the sand appear interdaily, any trace of human interference entirely fading away.",
    alt_description: "brown and white mountains under blue sky during daytime",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cool",
        title: "Cool Images & Photos",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1599887832271-23830d5dda3c?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1599887832271-23830d5dda3c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1599887832271-23830d5dda3c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1599887832271-23830d5dda3c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1599887832271-23830d5dda3c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1599887832271-23830d5dda3c",
    },
    links: {
      self: "https://api.unsplash.com/photos/brown-and-white-mountains-under-blue-sky-during-daytime-aQK3e0mH1g0",
      html: "https://unsplash.com/photos/brown-and-white-mountains-under-blue-sky-during-daytime-aQK3e0mH1g0",
      download:
        "https://unsplash.com/photos/aQK3e0mH1g0/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/aQK3e0mH1g0/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 353,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-10-07T09:48:05Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "nJG6ASdjZMA",
      updated_at: "2023-09-11T19:29:53Z",
      username: "tamiwanders",
      name: "Tamara Bravo",
      first_name: "Tamara",
      last_name: "Bravo",
      twitter_username: "tamiwanders",
      portfolio_url: null,
      bio: "Peruvian in love with nature, adventure and colourful things.\r\n Follow me on instagram! @tamiwanders",
      location: "Lima, Peru",
      links: {
        self: "https://api.unsplash.com/users/tamiwanders",
        html: "https://unsplash.com/@tamiwanders",
        photos: "https://api.unsplash.com/users/tamiwanders/photos",
        likes: "https://api.unsplash.com/users/tamiwanders/likes",
        portfolio: "https://api.unsplash.com/users/tamiwanders/portfolio",
        following: "https://api.unsplash.com/users/tamiwanders/following",
        followers: "https://api.unsplash.com/users/tamiwanders/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1600131124165-939b3a59eb0eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1600131124165-939b3a59eb0eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1600131124165-939b3a59eb0eimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "tamiwanders",
      total_collections: 0,
      total_likes: 0,
      total_photos: 8,
      total_promoted_photos: 2,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "tamiwanders",
        portfolio_url: null,
        twitter_username: "tamiwanders",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS REBEL T3i",
      name: "Canon, EOS REBEL T3i",
      exposure_time: "1/160",
      aperture: "9",
      focal_length: "30.0",
      iso: 100,
    },
    location: {
      name: "Huacachina, Peru",
      city: "Huacachina",
      country: "Peru",
      position: {
        latitude: -14.087459,
        longitude: -75.762586,
      },
    },
    views: 9640489,
    downloads: 87080,
  },
  {
    id: "2mjl2uvz9ic",
    slug: "a-black-and-white-photo-of-a-wavy-pattern-2mjl2uvz9ic",
    alternative_slugs: {
      en: "a-black-and-white-photo-of-a-wavy-pattern-2mjl2uvz9ic",
      es: "una-foto-en-blanco-y-negro-de-un-patron-ondulado-2mjl2uvz9ic",
      ja: "波状のパターンの白黒写真-2mjl2uvz9ic",
      fr: "une-photo-en-noir-et-blanc-dun-motif-ondule-2mjl2uvz9ic",
      it: "una-foto-in-bianco-e-nero-di-un-motivo-ondulato-2mjl2uvz9ic",
      ko: "물결-모양의-흑백-사진-2mjl2uvz9ic",
      de: "ein-schwarz-weiss-foto-eines-wellenmusters-2mjl2uvz9ic",
      pt: "uma-foto-em-preto-e-branco-de-um-padrao-ondulado-2mjl2uvz9ic",
    },
    created_at: "2019-07-02T11:06:04Z",
    updated_at: "2024-08-01T09:19:32Z",
    promoted_at: "2019-07-02T16:01:33Z",
    width: 7952,
    height: 5304,
    color: "#d9d9d9",
    blur_hash: "LML;me~qRjofofM{-;WBWBxuRjWB",
    description: null,
    alt_description: "a black and white photo of a wavy pattern",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "apps",
        title: "Apps Images & Photos",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "facebook",
        title: "Facebook Photos & Images",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1562065540-efa93744ed71?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1562065540-efa93744ed71?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1562065540-efa93744ed71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1562065540-efa93744ed71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1562065540-efa93744ed71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1562065540-efa93744ed71",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-black-and-white-photo-of-a-wavy-pattern-2mjl2uvz9ic",
      html: "https://unsplash.com/photos/a-black-and-white-photo-of-a-wavy-pattern-2mjl2uvz9ic",
      download:
        "https://unsplash.com/photos/2mjl2uvz9ic/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/2mjl2uvz9ic/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 739,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      "architecture-interior": {
        status: "approved",
        approved_on: "2020-04-06T14:20:14Z",
      },
      "textures-patterns": {
        status: "approved",
        approved_on: "2024-02-13T08:41:18Z",
      },
      wallpapers: {
        status: "approved",
        approved_on: "2020-04-06T14:20:09Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "r01XoGoEPT8",
      updated_at: "2024-07-27T11:48:36Z",
      username: "rgaleriacom",
      name: "Ricardo Gomez Angel",
      first_name: "Ricardo",
      last_name: "Gomez Angel",
      twitter_username: null,
      portfolio_url: "https://www.rgaleria.com",
      bio: "I'm architect, marketing specialist and photographer. I`m working since years as freelancer photographer for different Swiss companies",
      location: "Switzerland",
      links: {
        self: "https://api.unsplash.com/users/rgaleriacom",
        html: "https://unsplash.com/@rgaleriacom",
        photos: "https://api.unsplash.com/users/rgaleriacom/photos",
        likes: "https://api.unsplash.com/users/rgaleriacom/likes",
        portfolio: "https://api.unsplash.com/users/rgaleriacom/portfolio",
        following: "https://api.unsplash.com/users/rgaleriacom/following",
        followers: "https://api.unsplash.com/users/rgaleriacom/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1492187901140-48ac7eff801c?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "ricardogo03",
      total_collections: 0,
      total_likes: 16924,
      total_photos: 1576,
      total_promoted_photos: 453,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "ricardogo03",
        portfolio_url: "https://www.rgaleria.com",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM2",
      name: "SONY, ILCE-7RM2",
      exposure_time: "1/100",
      aperture: "13.0",
      focal_length: "177.0",
      iso: 160,
    },
    location: {
      name: "Metal abstract, Basel, Switzeland",
      city: "Basel",
      country: "Switzeland",
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 23898354,
    downloads: 70669,
  },
  {
    id: "1vYkQVDWXl0",
    slug: "person-with-red-umbrella-walking-on-street-during-nighttime-1vYkQVDWXl0",
    alternative_slugs: {
      en: "person-with-red-umbrella-walking-on-street-during-nighttime-1vYkQVDWXl0",
      es: "persona-con-paraguas-rojo-caminando-por-la-calle-durante-la-noche-1vYkQVDWXl0",
      ja: "赤い傘をさして夜間に通りを歩く人-1vYkQVDWXl0",
      fr: "personne-avec-un-parapluie-rouge-marchant-dans-la-rue-pendant-la-nuit-1vYkQVDWXl0",
      it: "persona-con-ombrello-rosso-che-cammina-sulla-strada-durante-la-notte-1vYkQVDWXl0",
      ko: "빨간-우산을-쓴-사람이-밤에-거리를-걷고-있습니다-1vYkQVDWXl0",
      de: "person-mit-rotem-regenschirm-geht-nachts-auf-der-strasse-spazieren-1vYkQVDWXl0",
      pt: "pessoa-com-guarda-chuva-vermelho-andando-na-rua-durante-a-noite-1vYkQVDWXl0",
    },
    created_at: "2015-05-28T18:07:36Z",
    updated_at: "2024-07-31T12:00:18Z",
    promoted_at: "2015-05-28T18:07:36Z",
    width: 5184,
    height: 3456,
    color: "#0c2640",
    blur_hash: "LNA,5.=xE#E*OnSxaeV[1HJR+_,?",
    description: "Walking Alone in the Rain",
    alt_description:
      "person with red umbrella walking on street during nighttime",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1432836431433-925d3cc0a5cd?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1432836431433-925d3cc0a5cd?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1432836431433-925d3cc0a5cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1432836431433-925d3cc0a5cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1432836431433-925d3cc0a5cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1432836431433-925d3cc0a5cd",
    },
    links: {
      self: "https://api.unsplash.com/photos/person-with-red-umbrella-walking-on-street-during-nighttime-1vYkQVDWXl0",
      html: "https://unsplash.com/photos/person-with-red-umbrella-walking-on-street-during-nighttime-1vYkQVDWXl0",
      download:
        "https://unsplash.com/photos/1vYkQVDWXl0/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/1vYkQVDWXl0/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 1459,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "_xatFNjMFGM",
      updated_at: "2024-07-31T12:02:18Z",
      username: "whileimout",
      name: "Gabe",
      first_name: "Gabe",
      last_name: null,
      twitter_username: "whileimout",
      portfolio_url: "https://whileimout.tumblr.com/",
      bio: "Designer / Art Director",
      location: "Amsterdam",
      links: {
        self: "https://api.unsplash.com/users/whileimout",
        html: "https://unsplash.com/@whileimout",
        photos: "https://api.unsplash.com/users/whileimout/photos",
        likes: "https://api.unsplash.com/users/whileimout/likes",
        portfolio: "https://api.unsplash.com/users/whileimout/portfolio",
        following: "https://api.unsplash.com/users/whileimout/following",
        followers: "https://api.unsplash.com/users/whileimout/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1711615140945-c2b6d378d26dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1711615140945-c2b6d378d26dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1711615140945-c2b6d378d26dimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "whileimout",
      total_collections: 0,
      total_likes: 0,
      total_photos: 128,
      total_promoted_photos: 31,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "whileimout",
        portfolio_url: "https://whileimout.tumblr.com/",
        twitter_username: "whileimout",
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 60D",
      name: "Canon, EOS 60D",
      exposure_time: "1/100",
      aperture: "1.8",
      focal_length: "50.0",
      iso: 400,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 42690735,
    downloads: 137347,
  },
  {
    id: "h7Oq4mAw7_I",
    slug: "selective-focus-photography-of-yellow-and-green-palm-plant-h7Oq4mAw7_I",
    alternative_slugs: {
      en: "selective-focus-photography-of-yellow-and-green-palm-plant-h7Oq4mAw7_I",
      es: "fotografia-de-enfoque-selectivo-de-plantas-de-palma-amarilla-y-verde-h7Oq4mAw7_I",
      ja: "黄色と緑のヤシ植物の選択焦点写真-h7Oq4mAw7_I",
      fr: "photographie-selective-de-mise-au-point-de-palmier-jaune-et-vert-h7Oq4mAw7_I",
      it: "fotografia-selettiva-della-messa-a-fuoco-della-pianta-di-palma-gialla-e-verde-h7Oq4mAw7_I",
      ko: "노란색과-녹색-야자-식물의-선택적-초점-사진-h7Oq4mAw7_I",
      de: "selektive-fokusfotografie-von-gelben-und-grunen-palmpflanzen-h7Oq4mAw7_I",
      pt: "fotografia-com-foco-seletivo-de-palmeiras-amarelas-e-verdes-h7Oq4mAw7_I",
    },
    created_at: "2019-07-04T07:07:12Z",
    updated_at: "2024-07-26T12:21:24Z",
    promoted_at: "2019-07-04T07:12:58Z",
    width: 4992,
    height: 7484,
    color: "#262626",
    blur_hash: "L86aO|fR0%azW=a|ofj[5SfQ=^j[",
    description: null,
    alt_description:
      "selective focus photography of yellow and green palm plant",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1562223906-b38e3f135742?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1562223906-b38e3f135742?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1562223906-b38e3f135742?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1562223906-b38e3f135742?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1562223906-b38e3f135742?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1562223906-b38e3f135742",
    },
    links: {
      self: "https://api.unsplash.com/photos/selective-focus-photography-of-yellow-and-green-palm-plant-h7Oq4mAw7_I",
      html: "https://unsplash.com/photos/selective-focus-photography-of-yellow-and-green-palm-plant-h7Oq4mAw7_I",
      download:
        "https://unsplash.com/photos/h7Oq4mAw7_I/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/h7Oq4mAw7_I/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 93,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2020-05-22T12:56:08Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "JaWOZOuwjwU",
      updated_at: "2024-06-05T01:20:22Z",
      username: "guogete",
      name: "和国 谢",
      first_name: "和国",
      last_name: "谢",
      twitter_username: null,
      portfolio_url: null,
      bio: "Hello! I am xie heguo",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/guogete",
        html: "https://unsplash.com/@guogete",
        photos: "https://api.unsplash.com/users/guogete/photos",
        likes: "https://api.unsplash.com/users/guogete/likes",
        portfolio: "https://api.unsplash.com/users/guogete/portfolio",
        following: "https://api.unsplash.com/users/guogete/following",
        followers: "https://api.unsplash.com/users/guogete/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1610554622672-d7c9968b8448image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1610554622672-d7c9968b8448image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1610554622672-d7c9968b8448image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "guogete",
      total_collections: 0,
      total_likes: 1,
      total_photos: 356,
      total_promoted_photos: 81,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "guogete",
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM3",
      name: "SONY, ILCE-7RM3",
      exposure_time: "1/60",
      aperture: "6.3",
      focal_length: "50.0",
      iso: 125,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 6254495,
    downloads: 5823,
  },
  {
    id: "SUhVPA9eNYo",
    slug: "a-mountain-range-with-a-lake-in-the-foreground-SUhVPA9eNYo",
    alternative_slugs: {
      en: "a-mountain-range-with-a-lake-in-the-foreground-SUhVPA9eNYo",
      es: "una-cadena-montanosa-con-un-lago-en-primer-plano-SUhVPA9eNYo",
      ja: "湖を前にした連峦-SUhVPA9eNYo",
      fr: "une-chaine-de-montagnes-avec-un-lac-au-premier-plan-SUhVPA9eNYo",
      it: "una-catena-montuosa-con-un-lago-in-primo-piano-SUhVPA9eNYo",
      ko: "전경에-호수가-있는-산맥-SUhVPA9eNYo",
      de: "ein-gebirgszug-mit-einem-see-im-vordergrund-SUhVPA9eNYo",
      pt: "uma-cordilheira-com-um-lago-em-primeiro-plano-SUhVPA9eNYo",
    },
    created_at: "2024-07-18T01:21:40Z",
    updated_at: "2024-08-01T01:42:33Z",
    promoted_at: "2024-07-18T07:59:51Z",
    width: 3020,
    height: 4027,
    color: "#262626",
    blur_hash: "LpD0_nRjofWB?wRjoeaykCj]WVj[",
    description: null,
    alt_description: "A mountain range with a lake in the foreground",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1721265576450-2c4782996dfe?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1721265576450-2c4782996dfe?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1721265576450-2c4782996dfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1721265576450-2c4782996dfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1721265576450-2c4782996dfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1721265576450-2c4782996dfe",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-mountain-range-with-a-lake-in-the-foreground-SUhVPA9eNYo",
      html: "https://unsplash.com/photos/a-mountain-range-with-a-lake-in-the-foreground-SUhVPA9eNYo",
      download:
        "https://unsplash.com/photos/SUhVPA9eNYo/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/SUhVPA9eNYo/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 43,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: {
        status: "approved",
        approved_on: "2024-07-18T17:53:19Z",
      },
    },
    asset_type: "photo",
    user: {
      id: "sd-_3jJwYiA",
      updated_at: "2024-08-01T01:42:39Z",
      username: "gabrieluizramos",
      name: "Gabriel Ramos",
      first_name: "Gabriel",
      last_name: "Ramos",
      twitter_username: "gabrieluizramos",
      portfolio_url: "https://fotografia.gabrieluizramos.com.br/",
      bio: "Just a metalhead kid shooting with different sorts of gadgets",
      location: "São Paulo, Brazil",
      links: {
        self: "https://api.unsplash.com/users/gabrieluizramos",
        html: "https://unsplash.com/@gabrieluizramos",
        photos: "https://api.unsplash.com/users/gabrieluizramos/photos",
        likes: "https://api.unsplash.com/users/gabrieluizramos/likes",
        portfolio: "https://api.unsplash.com/users/gabrieluizramos/portfolio",
        following: "https://api.unsplash.com/users/gabrieluizramos/following",
        followers: "https://api.unsplash.com/users/gabrieluizramos/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1694725605255-1144adf6c001image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1694725605255-1144adf6c001image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1694725605255-1144adf6c001image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "gabrieluizramos",
      total_collections: 16,
      total_likes: 1070,
      total_photos: 739,
      total_promoted_photos: 67,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "gabrieluizramos",
        portfolio_url: "https://fotografia.gabrieluizramos.com.br/",
        twitter_username: "gabrieluizramos",
        paypal_email: null,
      },
    },
    exif: {
      make: "DJI",
      model: "FC3582",
      name: "DJI, FC3582",
      exposure_time: "1/1250",
      aperture: "1.7",
      focal_length: "6.7",
      iso: 100,
    },
    location: {
      name: "Condoriri, Bolivia",
      city: "Condoriri",
      country: "Bolivia",
      position: {
        latitude: -17.533333,
        longitude: -67.233333,
      },
    },
    views: 1582659,
    downloads: 23098,
  },
  {
    id: "wG7SGxxzj24",
    slug: "a-rocky-beach-with-a-body-of-water-and-a-rocky-shore-wG7SGxxzj24",
    alternative_slugs: {
      en: "a-rocky-beach-with-a-body-of-water-and-a-rocky-shore-wG7SGxxzj24",
      es: "una-playa-rocosa-con-un-cuerpo-de-agua-y-una-orilla-rocosa-wG7SGxxzj24",
      ja: "水域と岩だらけの海岸がある岩だらけのビーチ-wG7SGxxzj24",
      fr: "une-plage-rocheuse-avec-un-plan-deau-et-un-rivage-rocheux-wG7SGxxzj24",
      it: "una-spiaggia-rocciosa-con-uno-specchio-dacqua-e-una-costa-rocciosa-wG7SGxxzj24",
      ko: "수역과-바위가-많은-해안이있는-바위-해변-wG7SGxxzj24",
      de: "ein-felsiger-strand-mit-einem-gewasser-und-einem-felsigen-ufer-wG7SGxxzj24",
      pt: "uma-praia-rochosa-com-um-corpo-de-agua-e-uma-costa-rochosa-wG7SGxxzj24",
    },
    created_at: "2022-07-25T06:03:10Z",
    updated_at: "2024-07-26T10:37:08Z",
    promoted_at: "2022-07-28T03:40:01Z",
    width: 4127,
    height: 6190,
    color: "#c0c0a6",
    blur_hash: "LXJ[Cb-;E1of.Tofaxj@9HM{xtRk",
    description: null,
    alt_description: "a rocky beach with a body of water and a rocky shore",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1658728942273-c50f74405051?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1658728942273-c50f74405051?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1658728942273-c50f74405051?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1658728942273-c50f74405051?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1658728942273-c50f74405051?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1658728942273-c50f74405051",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-rocky-beach-with-a-body-of-water-and-a-rocky-shore-wG7SGxxzj24",
      html: "https://unsplash.com/photos/a-rocky-beach-with-a-body-of-water-and-a-rocky-shore-wG7SGxxzj24",
      download:
        "https://unsplash.com/photos/wG7SGxxzj24/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/wG7SGxxzj24/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 111,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "5nWio-aFX3c",
      updated_at: "2024-07-23T12:10:03Z",
      username: "bundo",
      name: "Bundo Kim",
      first_name: "Bundo",
      last_name: "Kim",
      twitter_username: null,
      portfolio_url: "http://instagram.com/j__kyung/",
      bio: "Hope you have a nice photo!",
      location: "Seoul, Korea",
      links: {
        self: "https://api.unsplash.com/users/bundo",
        html: "https://unsplash.com/@bundo",
        photos: "https://api.unsplash.com/users/bundo/photos",
        likes: "https://api.unsplash.com/users/bundo/likes",
        portfolio: "https://api.unsplash.com/users/bundo/portfolio",
        following: "https://api.unsplash.com/users/bundo/following",
        followers: "https://api.unsplash.com/users/bundo/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1522243949591-75c7f5ac1ffb?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1522243949591-75c7f5ac1ffb?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1522243949591-75c7f5ac1ffb?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "j__kyung",
      total_collections: 6,
      total_likes: 26,
      total_photos: 1334,
      total_promoted_photos: 208,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "j__kyung",
        portfolio_url: "http://instagram.com/j__kyung/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "FUJIFILM",
      model: "X-Pro3",
      name: "FUJIFILM, X-Pro3",
      exposure_time: "1/2500",
      aperture: "1.0",
      focal_length: "35.0",
      iso: 160,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: {
        latitude: null,
        longitude: null,
      },
    },
    views: 4431017,
    downloads: 36320,
  },
  {
    id: "MLN_ZwWQneU",
    slug: "a-snow-covered-mountain-range-with-birds-flying-over-it-MLN_ZwWQneU",
    alternative_slugs: {
      en: "a-snow-covered-mountain-range-with-birds-flying-over-it-MLN_ZwWQneU",
      es: "una-cadena-montanosa-cubierta-de-nieve-con-pajaros-volando-sobre-ella-MLN_ZwWQneU",
      ja: "雪に覆われた山脈とその上空を飛ぶ鳥たち-MLN_ZwWQneU",
      fr: "une-chaine-de-montagnes-enneigee-avec-des-oiseaux-qui-la-survolent-MLN_ZwWQneU",
      it: "una-catena-montuosa-innevata-con-uccelli-che-volano-sopra-di-essa-MLN_ZwWQneU",
      ko: "새들이-날아다니는-눈-덮인-산맥-MLN_ZwWQneU",
      de: "eine-schneebedeckte-bergkette-uber-die-vogel-fliegen-MLN_ZwWQneU",
      pt: "uma-cordilheira-coberta-de-neve-com-passaros-voando-sobre-ela-MLN_ZwWQneU",
    },
    created_at: "2024-02-06T20:11:00Z",
    updated_at: "2024-07-26T11:12:48Z",
    promoted_at: "2024-02-09T15:09:07Z",
    width: 7043,
    height: 4695,
    color: "#a6c0c0",
    blur_hash: "LaI#[YWCWVR*.TkCayaynhoJayof",
    description:
      "Shot while filming our short film which compares a photographer's dark room to the difficult seasons we face in our lives. Watch 'Darkroom' on our website: https://www.bravingbird.com/films/darkroom",
    alt_description: "a snow covered mountain range with birds flying over it",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1707249700537-7a2e4004a139?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1707249700537-7a2e4004a139?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1707249700537-7a2e4004a139?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1707249700537-7a2e4004a139?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1707249700537-7a2e4004a139?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1707249700537-7a2e4004a139",
    },
    links: {
      self: "https://api.unsplash.com/photos/a-snow-covered-mountain-range-with-birds-flying-over-it-MLN_ZwWQneU",
      html: "https://unsplash.com/photos/a-snow-covered-mountain-range-with-birds-flying-over-it-MLN_ZwWQneU",
      download:
        "https://unsplash.com/photos/MLN_ZwWQneU/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
      download_location:
        "https://api.unsplash.com/photos/MLN_ZwWQneU/download?ixid=M3w2MzkyMjV8MHwxfHJhbmRvbXx8fHx8fHx8fDE3MjI1MTA2MDR8",
    },
    likes: 101,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "NEl0UgeioJQ",
      updated_at: "2024-06-19T01:25:12Z",
      username: "bravingbird",
      name: "Bravingbird",
      first_name: "Bravingbird",
      last_name: null,
      twitter_username: null,
      portfolio_url: "https://www.bravingbird.com/",
      bio: "🎞️ We make free films designed to be shared and to spark conversations.\r\n➡️ Every story we tell is made available for free to be experienced, used, and shared by anyone to help start meaningful discussions and pass on powerful ideas.",
      location: "West Dundee, IL",
      links: {
        self: "https://api.unsplash.com/users/bravingbird",
        html: "https://unsplash.com/@bravingbird",
        photos: "https://api.unsplash.com/users/bravingbird/photos",
        likes: "https://api.unsplash.com/users/bravingbird/likes",
        portfolio: "https://api.unsplash.com/users/bravingbird/portfolio",
        following: "https://api.unsplash.com/users/bravingbird/following",
        followers: "https://api.unsplash.com/users/bravingbird/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1709663415667-5d924262fdb9image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1709663415667-5d924262fdb9image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1709663415667-5d924262fdb9image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "bravingbird",
      total_collections: 0,
      total_likes: 0,
      total_photos: 76,
      total_promoted_photos: 20,
      total_illustrations: 0,
      total_promoted_illustrations: 0,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "bravingbird",
        portfolio_url: "https://www.bravingbird.com/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "ILCE-7RM5",
      name: "SONY, ILCE-7RM5",
      exposure_time: "1/250",
      aperture: "6.3",
      focal_length: "70.0",
      iso: 100,
    },
    location: {
      name: "Grand Teton National Park, Wyoming, USA",
      city: null,
      country: "United States",
      position: {
        latitude: 43.790428,
        longitude: -110.681763,
      },
    },
    views: 4153647,
    downloads: 20608,
  },
];
